### PR TITLE
[#1139] Handle Event Log Cert Issue

### LINKED ISSUE #1131: RIM Upload fails
Upload files from the RIM Page fails to upload either a Base RIM or Support RIM file.

### LINKED ISSUE #1139: Catch errors in cert parsing during event log processing and pass up to the ACA
When there is an issue parsing a certificate found in the event log, the code throws an exception. Need to catch this exception and 1) pass it up to the ACA for display, 2) not stop validation from processing.

### PR DESCRIPTION
**Pull request by iadgovuser58**
### Description
When an EventLog of type EV_EFI_VARIABLE_DRIVER_CONFIG, UEFI_VARIABLE_DATA name "PK" contains a cert that isn't able to be processed, need to store that error (for print in eventlog tool, and for ACA display in ACA) but not stop validation from continuing.

---

### Test Instructions:
1. Run the ACA.
2. Upload support RIM which contains this particular event with a cert that isn't parsable.
3. Verify that the display still shows this event along with an error stating the non-parsable cert.
4. Run eventlogtool and verify the print still shows this event along with an error stating the non-parsable cert.

---

### Summary Of Changes:
1. In the UefiX509Cert class, catch the error, add the error message, and rethrow. 
2. In the calling class, UefiSignatureData, catch the error and 1) store it in the toString, 2) log it in the ACA log as a warning. Then continue.
3. Cleaned up some repeated code, and incorrect cert buffer size, and comments that had gotten misaligned.

---

### Issues This PR Addresses:
Closes #1139
Closes #1131

### CODE REVIEW

File: HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/uefi/UefiSignatureList.java [hunk 1]
```diff
@@ -5,22 +5,21 @@
...
 
 /**
  * Class for processing either
- * 1) the contents of a Secure Boot PK, KEK, DB or DBX contents,
- * used for EFIVariables associated with Secure Boot,
- * as defined by Section 32.4.1 Signature Database from the UEFI 2.8 specification
- * 2) the contents of an SPDM devdb,
- * used for SPDM Device Policy, whose data is an EFIVariable
- * as defined by PFP v1.06 Rev52, Section 10.4
+ *   1) the contents of a Secure Boot PK, KEK, DB or DBX contents,
```
Comment (ThatSilentCoder) [inline HIRS_Utils/src/main/java/hirs/utils/tpm/eventlog/uefi/UefiSignatureList.java]: Same comment as above:

If you want your Javadocs to preserve the numbering or bullet structure exactly as shown, you can either:

1. Wrap the content in `<pre>...</pre>` to preserve formatting.
2. Use HTML list tags `<ul><li>...</li></ul>` for proper bullets.
