### PR TITLE
[#924] Fix DataTable Columns Sortability Issue

### LINKED ISSUE #924: Data Table Columns Not Sortable (Orderability Issue)
Currently, our data tables lack support for sorting (orderability), making it difficult for users to efficiently navigate and view the data in a desired order. Implementing orderability will enhance the user experience by allowing users to sort the data based on specific columns in ascending or descending order.

### PR DESCRIPTION
**Pull request by ThatSilentCoder**
### Description
The focus of this issue was to resolve the sortability problem and enable users to sort columns with sortable headers.

### Test Instructions:

1. **Run the ACA** using your preferred method.
2. **Verify column sorting**:

   * Go to each page and ensure that you can sort each table column.
   * Confirm no errors occur during sorting.
3. **Test search functionality**:

   * Use either the column search dropdown or the global search textbox to search for records.
   * Ensure you can still sort the filtered records.
4. **Reset sorting**:

   * After sorting a column, verify that clicking the "Clear All" button resets the sorting.

### Issues This PR Addresses:
Closes #924

### CODE REVIEW

File: HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/datatables/Order.java [hunk 1]
```diff
@@ -8,49 +8,31 @@
...
-
-    /**
-     * @return true if ascending order, false otherwise.
+     * The name of the column to which ordering is applied.
      */
-    public boolean isAscending() {
-        return dir.equalsIgnoreCase("asc");
-    }
+    @NotNull
+    private String name;
```
Comment (ThatSilentCoder) [inline HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/datatables/Order.java]: Added missing property.

File: HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/DevicePageController.java [hunk 2]
```diff
@@ -88,22 +91,70 @@ public DataTableResponse<HashMap<String, Object>> getDevicesTableData(
...
+                = this.devicePageService.retrieveDevicesAndAssociatedCertificates(deviceList);
+
+        log.info("Returning the size of the filtered list of devices: {}",
+                devicesAndAssociatedCertificates.size());
+        return new DataTableResponse<>(devicesAndAssociatedCertificates, dataTableInput);
+    }
+
+
+    /**
+     * Helper method that retrieves a filtered and paginated list of devices based on the provided search criteria.
```
Comment (ThatSilentCoder) [inline HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/DevicePageController.java]: Moved this logic out of the list method so the list method would not be so cluttered.

File: HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/IDevIdCertificatePageController.java [hunk 3]
```diff
@@ -292,4 +255,82 @@ public RedirectView deleteIdevIdCertificate(@RequestParam final String id, final
...
+     * @param globalSearchTerm          A global search term that will be used to filter the idevid certificates
+     *                                  by the searchable fields.
+     * @param columnsWithSearchCriteria A set of columns with specific search criteria entered by the user.
+     * @param searchableColumnNames     A set of searchable column names that are  for the global search term.
+     * @param pageable                  pageable
+     * @return A {@link FilteredRecordsList} containing the filtered and paginated list of
+     * idevid certificates, along with the total number of records and the number of records matching the
+     * filter criteria.
+     */
+    private FilteredRecordsList<IDevIDCertificate> getFilteredIDevIdCertificateList(
```
Comment (ThatSilentCoder) [inline HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/IDevIdCertificatePageController.java]: Moved this logic out of the list method so the list method would not be so cluttered.

File: HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/IssuedCertificatePageController.java [hunk 4]
```diff
@@ -259,4 +220,85 @@ public RedirectView deleteIssuedCertificate(@RequestParam final String id, final
         model.put(MESSAGES_ATTRIBUTE, messages);
         return redirectTo(Page.ISSUED_CERTIFICATES, new NoPageParams(), model, attr);
     }
+
+    /**
+     * Helper method that retrieves a filtered and paginated list of issued certificates based on the
```
Comment (ThatSilentCoder) [inline HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/IssuedCertificatePageController.java]: Moved this logic out of the list method so the list method would not be so cluttered.

File: HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/PlatformCredentialPageController.java [hunk 5]
```diff
@@ -313,4 +273,84 @@ public RedirectView deletePlatformCredential(@RequestParam final String id,
         model.put(MESSAGES_ATTRIBUTE, messages);
         return redirectTo(Page.PLATFORM_CREDENTIALS, new NoPageParams(), model, attr);
     }
+
+    /**
+     * Helper method that retrieves a filtered and paginated list of endorsement credentials based on the
```
Comment (ThatSilentCoder) [inline HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/PlatformCredentialPageController.java]: Moved this logic out of the list method so the list method would not be so cluttered.

File: HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/RimDatabasePageController.java [hunk 6]
```diff
@@ -89,17 +92,72 @@ public DataTableResponse<ReferenceDigestValue> getRDVTableData(
...
+     * @param globalSearchTerm          A global search term that will be used to filter the endorsement
+     *                                  credentials by the searchable fields.
+     * @param columnsWithSearchCriteria A set of columns with specific search criteria entered by the user.
+     * @param searchableColumnNames     A set of searchable column names that are  for the global search term.
+     * @param pageable                  pageable
+     * @return A {@link FilteredRecordsList} containing the filtered and paginated list of
+     * reference digest values , along with the total number of records and the number of records matching the
+     * filter criteria.
+     */
+    private FilteredRecordsList<ReferenceDigestValue> getFilteredRDVList(
```
Comment (ThatSilentCoder) [inline HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/RimDatabasePageController.java]: Moved this logic out of the list method so the list method would not be so cluttered.

File: HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/TrustChainCertificatePageController.java [hunk 7]
```diff
@@ -380,4 +341,85 @@ public RedirectView deleteTrustChainCertificate(@RequestParam final String id,
         model.put(MESSAGES_ATTRIBUTE, messages);
         return redirectTo(Page.TRUST_CHAIN, new NoPageParams(), model, attr);
     }
+
+    /**
+     * Helper method that retrieves a filtered and paginated list of trust chain certificates based on the
```
Comment (ThatSilentCoder) [inline HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/TrustChainCertificatePageController.java]: Moved this logic out of the list method so the list method would not be so cluttered.

File: HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/EndorsementCredentialPageController.java [hunk 8]
```diff
@@ -110,59 +113,19 @@ public DataTableResponse<EndorsementCredential> getEndorsementCredentialsTableDa
...
-        final int currentPage = dataTableInput.getStart() / dataTableInput.getLength();
-        int pageSize = dataTableInput.getLength();
-
-        // If pageSize is -1 (Show All), set a very large page size
-        if (pageSize == -1) {
-            pageSize = Integer.MAX_VALUE;
-        }
-
-        Pageable pageable = PageRequest.of(currentPage, pageSize);
+        Pageable pageable = ControllerPagesUtils.createPageableObject(
```
Comment (ThatSilentCoder) [inline HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/EndorsementCredentialPageController.java]: Moved the logic to creating a pagination object to a common class so that it may be used the same way across all controller classes.

File: HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/DevicePageController.java [hunk 9]
```diff
@@ -88,22 +91,70 @@ public DataTableResponse<HashMap<String, Object>> getDevicesTableData(
...
-        if (pageSize == -1) {
-            pageSize = Integer.MAX_VALUE;
+        // since the column names are typically pre-fixed with the word `device.`, we need to...
+        if (orderColumn != null && orderColumn.getName().startsWith("device.")) {
+            // Take the part after `device.`
+            orderColumn.setName(orderColumn.getName().split("device.")[1]);
         }
 
-        Pageable pageable = PageRequest.of(currentPage, pageSize);
+        Pageable pageable = ControllerPagesUtils.createPageableObject(
```
Comment (ThatSilentCoder) [inline HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/DevicePageController.java]: Moved the logic to creating a pagination object to a common class so that it may be used the same way across all controller classes.

File: HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/IssuedCertificatePageController.java [hunk 10]
```diff
@@ -110,61 +113,19 @@ public DataTableResponse<IssuedAttestationCertificate> getIssuedCertificatesTabl
...
-        final int currentPage = dataTableInput.getStart() / dataTableInput.getLength();
-        int pageSize = dataTableInput.getLength();
-
-        // If pageSize is -1 (Show All), set a very large page size
-        if (pageSize == -1) {
-            pageSize = Integer.MAX_VALUE;
-        }
-
-        Pageable pageable = PageRequest.of(currentPage, pageSize);
+        Pageable pageable = ControllerPagesUtils.createPageableObject(
```
Comment (ThatSilentCoder) [inline HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/IssuedCertificatePageController.java]: Moved the logic to creating a pagination object to a common class so that it may be used the same way across all controller classes.

File: HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/ValidationReportsPageController.java [hunk 11]
```diff
@@ -91,18 +94,70 @@ public DataTableResponse<SupplyChainValidationSummary> getValidationReportsTable
                         SupplyChainValidationSummary.class,
                         dataTableInput.getColumns());
 
-        final int currentPage = dataTableInput.getStart() / dataTableInput.getLength();
-        int pageSize = dataTableInput.getLength();
+        Pageable pageable = ControllerPagesUtils.createPageableObject(
```
Comment (ThatSilentCoder) [inline HIRS_AttestationCAPortal/src/main/java/hirs/attestationca/portal/page/controllers/ValidationReportsPageController.java]: Moved the logic to creating a pagination object to a common class so that it may be used the same way across all controller classes.
