### PR TITLE
[#1090] Fix ACA Provisioning Issue When Using ECC Key

### LINKED ISSUE #1090: Fix ACA provision using ecc key
When using aca_setup.sh using the -aa ecc parameter it sets the ACA certificate chain to and ecc 512 with sha384. There is an issue when provisioning using an ecc cert:
~~~
ERROR : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: hirs.attestationca.persist.exceptions.CertificateProcessingException: Encountered error while generating identity credential: cannot create signer: Supplied key (sun.security.ec.ECPrivateKeyImpl) is not a RSAPrivateKey instance] with root cause
java.security.InvalidKeyException: Supplied key (sun.security.ec.ECPrivateKeyImpl) is not a RSAPrivateKey instance
~~~ 
The ACA needs to be updated to handle ecc keys, or more importantly made crypt agile so it can use mldsa keys in the future.

Note that the ACA will currently show the provision as passing, yet won't create a new cert for the client. ACA should show that as a failure.

### PR DESCRIPTION
**Pull request by ThatSilentCoder**
### Description
Fix exceptions caused by provisioning against the ACA that is setup using the ECC key parameter in the setup script.

---

### Test Instructions:
1. Remove your local setup of the ACA using the follwing commands:

On Linux: 
```
sudo package/linux/aca/aca_remove_setup.sh
```

On Windows (Powershell 7 Core in Admin mode):
```
package\win\aca\aca_remove_setup.ps1
```

2. Setup the ACA to use ECC keys as follows:

On Linux: 
```
sudo package/linux/aca/aca_setup.sh -aa ecc -u
```

On Windows (Powershell 7 Core in Admin mode):
```
package\win\aca\aca_setup.ps1 -aa ecc -u
```

3. If everything is configured correctly, run the ACA.
4. Run the provisioner against the ACA for different policy settings: no policy enabled, platform credential
validation enabled, endorsement credential validation enabled, firmware validation enabled.
5. Verify that for each policy setting, assuming you've uploaded the correct certificates/RIMS up to the ACA per policy, the provisioning succeeds and that the ACA produces two issued certificates.
6. Verify that for each policy setting, no exceptions/errors are thrown in the console/logs.

---
### Summary Of Changes:

- Added the `-aca-alg`, `-ta-alg`, and `-db-alg` parameters to the PowerShell scripts to enable ACA setup on Windows using both ECC and RSA. Since introducing these parameters required updates across multiple scripts, additional fixes were made to address improper PowerShell syntax, along with general formatting improvements to the .ps1 files.

- Used the ShellCheck plugin while updating portions of the Bash scripts to address warnings and potential issues. Also improved the help menu output for better usability.

- ACA can now determine the type of keys being provided, rather than assuming all keys are RSA, and supports handling both ECC and RSA during the provisioning process.
---

### Issues This PR Addresses:
Closes #1090

### CODE REVIEW

File: HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/provision/service/AttestationCertificateAuthorityService.java [hunk 1]
```diff
@@ -1,9 +1,9 @@
-package hirs.attestationca.persist;
+package hirs.attestationca.persist.provision.service;
 
 /**
- * Defines the responsibilities of the Attestation Certificate Authority.
+ * Interface that defines the responsibilities of the Attestation Certificate Authority service.
  */
-public interface RestfulInterface {
+public interface AttestationCertificateAuthorityService {
```
Comment (ThatSilentCoder) [inline HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/provision/service/AttestationCertificateAuthorityService.java]: Renamed the interface class to better reflect its purpose.

File: HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/provision/service/CertificateRequestProcessorService.java [hunk 2]
```diff
@@ -387,4 +448,88 @@ private AppraisalStatus.Status doQuoteValidation(final Device device) {
...
+                    + "identity credential: " + exception.getMessage(), exception);
+        }
+    }
+
+    /**
+     * Returns a string representation of the signature algorithm that will be used with the provided private key.
+     *
+     * @return signature algorithm associated with the private key
+     */
+    private String getSignatureAlgorithm() {
```
Comment (ThatSilentCoder) [inline HIRS_AttestationCA/src/main/java/hirs/attestationca/persist/provision/service/CertificateRequestProcessorService.java]: This function resolves the issue.

**Review by iadgovuser59 — CHANGES_REQUESTED** [review]
I would say that the core shell scripts and TLS portion look good as written, but I'm wondering if we might need to clarify the scope of this PR a bit?

I'd say that the ProvisionUtils.java ECC changes appear to be more of an experimental piece which may require coordination with the Provisioner (currently with some RSA-shaped logic), so my suggestion might be to trim down the PR to only the required portions (perhaps removing or separating some of the refactoring and TPM-specific ECC provisioning portions for now).
